version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/start.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
